import { Inter } from "next/font/google";
import "../styles/globals.css";
import BottomNav from "@/components/BottomNav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="mx-auto max-w-md dark:bg-white">
      <body className={`${inter.className} shadow-2xl mb-8`}>
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
