import { Inter } from "next/font/google";
import "../styles/globals.css";
import BottomNav from "@/components/BottomNav/page";
import { Suspense } from "react";
import SkeletonList from "@/components/Skeleton/List";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Financial App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="mx-auto max-w-md bg-white">
      <body className={`${inter.className} shadow-2xl bg-white min-h-screen`}>
        {/* <Suspense fallback={<SkeletonList listNumber={15} />}> */}
        <div className="mb-10">{children}</div>
        {/* </Suspense> */}
        <BottomNav />
      </body>
    </html>
  );
}
